Configuratron:
  use_only:
    - mmidb
    # - bci_iv_2a
    # - ern
    # - erpbci
    # - sleep-edf
  preload: True
  sfreq: 256
  deep1010:
    return_mask: False

use_gpu: False
test_fraction: 0.5

encoder_weights: /Volumes/Data/encoder.pt
context_weights: /Volumes/Data/contextualizer.pt

datasets:
  mmidb:
    name: "Physionet MMIDB"
    toplevel: /Volumes/Data/MMI
    tmin: 0
    tlen: 6
    data_max: 0.001
    data_min: -0.001
    events:
      - T1
      - T2
    exclude_sessions:
      - "*R0[!48].edf"  # equivalently "*R0[1235679].edf"
      - "*R1[!2].edf"   # equivalently "*R1[134].edf"
    exclude_people:
      - S088
      - S090
      - S092
      - S100
    train_params:
      epochs: 7
      batch_size: 4
    folds: 5
    lr: 0.0001